check:
  - thoth-build
build:
  base-image: "quay.io/harshad16/s2i-minimal-notebook:dev"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "harshad16"
  registry-project: "s2i-lab-elyra"
  registry-secret: "thoth-station-thoth-pusher-secret"
